# Generated by Django 5.2.15 on 2026-06-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('eyebrow', models.CharField(default='current folder', max_length=120)),
                ('status', models.CharField(choices=[('current', 'Current'), ('past', 'Past'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('release_label', models.CharField(blank=True, max_length=120)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-released_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=120, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold out'), ('hidden', 'Hidden')], default='available', max_length=20)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('price_amount', models.PositiveIntegerField(default=0)),
                ('price_currency', models.CharField(default='RUB', max_length=12)),
                ('price_display', models.CharField(blank=True, max_length=80)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('stock_label', models.CharField(blank=True, max_length=120)),
                ('stock_unit', models.CharField(choices=[('piece', 'Piece'), ('set', 'Set')], default='piece', max_length=20)),
                ('main_image', models.ImageField(blank=True, upload_to='products/')),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('emotional_description', models.TextField(blank=True)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('size', models.CharField(blank=True, max_length=240)),
                ('care', models.JSONField(blank=True, default=list)),
                ('delivery', models.TextField(blank=True)),
                ('window_title', models.CharField(default='product.exe', max_length=120)),
                ('available_cta_label', models.CharField(default='Забрать', max_length=80)),
                ('sold_out_cta_label', models.CharField(default='Смотреть', max_length=80)),
                ('sort_order', models.IntegerField(default=100)),
                ('archive_caption', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to='catalog.drop')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='drop',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='listed_drops', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.IntegerField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
