# Generated by Django 5.2.15 on 2026-06-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=80, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=80)),
                ('social', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=160)),
                ('delivery', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
