# Generated by Django 5.2.15 on 2026-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Cosmo Beads', max_length=120)),
                ('instagram_url', models.URLField(default='https://instagram.com/cosmobeads.jewelry')),
                ('telegram_url', models.URLField(default='https://t.me/cosmobeadsjewelry')),
                ('contact_label', models.CharField(default='IG/TG', max_length=80)),
                ('default_meta_title', models.CharField(default='Cosmo Beads - handmade Y2K bead pieces', max_length=180)),
                ('default_meta_description', models.TextField(default='Cosmo Beads - handmade Y2K bead jewelry and accessories from a tiny cosmic drop.')),
                ('delivery_text', models.TextField(default='Доставка по России СДЭК/Почтой России после подтверждения заказа.')),
                ('order_success_text', models.TextField(default='Заявка отправлена. Мы свяжемся с тобой в Telegram или Instagram, подтвердим наличие, оплату и доставку.')),
                ('order_contact_explanation', models.TextField(default='После заявки мы подтвердим наличие, доставку и оплату вручную в Telegram или Instagram.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
